artifact_location: file:///D:/ML/Credit card fraud detection/%MLFLOW_TRACKING_URI%/0
creation_time: 1742302900902
experiment_id: '0'
last_update_time: 1742302900902
lifecycle_stage: active
name: Default
